Repository vuestorefront/storefront-ui, pull requests merged in 2020-10, with the labels that each got.

#1416 fix: type for SfButton in SfModal
  packages/vue/src/components/molecules/SfModal/SfModal.vue
Labels: review required

#1458 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: review required

#1359 refactor: pages
  packages/shared/icons/error.svg
  packages/shared/styles/components/organisms/SfSidebar.scss
  packages/vue/docs/getting-started/customization.md
  packages/vue/public/assets/storybook/Home/bannerC.jpg
  packages/vue/src/examples/pages/cart/Cart.vue
  packages/vue/src/examples/pages/category/Category.vue
  packages/vue/src/examples/pages/checkout/Checkout.vue
  packages/vue/src/examples/pages/checkout/_internal/ConfirmOrder.vue
  packages/vue/src/examples/pages/checkout/_internal/OrderReview.vue
  packages/vue/src/examples/pages/checkout/_internal/OrderSummary.vue
  packages/vue/src/examples/pages/checkout/_internal/Payment.vue
  packages/vue/src/examples/pages/checkout/_internal/PersonalDetails.vue
  packages/vue/src/examples/pages/checkout/_internal/Shipping.vue
  packages/vue/src/examples/pages/detailed-cart/DetailedCart.vue
  packages/vue/src/examples/pages/detailed-cart/_internal/OrderSummary.vue
  packages/vue/src/examples/pages/error/Error.vue
  packages/vue/src/examples/pages/home/Home.vue
  packages/vue/src/examples/pages/my-account/MyAccount.vue
  packages/vue/src/examples/pages/my-account/_internal/LoyaltyCard.vue
  packages/vue/src/examples/pages/my-account/_internal/MyNewsletter.vue
  packages/vue/src/examples/pages/my-account/_internal/MyProfile.vue
  packages/vue/src/examples/pages/my-account/_internal/MyReviews.vue
  packages/vue/src/examples/pages/my-account/_internal/OrderHistory.vue
  packages/vue/src/examples/pages/my-account/_internal/ShippingDetails.vue
  packages/vue/src/examples/pages/product/Product.vue
  packages/vue/src/examples/pages/thank-you/ThankYou.vue
Labels: ready to merge

#1460 fix: SfSelect: clicking on an option results in another being selected instead on MacOS
  packages/shared/styles/components/molecules/SfSelect.scss
Labels: review required

#1383 fix: SfButton native link in disabled state
  packages/shared/styles/components/atoms/SfButton.scss
  packages/vue/src/components/atoms/SfButton/SfButton.vue
Labels: hacktoberfest-accepted, ready to merge

#1406 fix: stories in SfPagination fixed
  packages/vue/src/components/molecules/SfPagination/SfPagination.stories.js
  packages/vue/src/components/molecules/SfPagination/SfPagination.vue
Labels: hacktoberfest-accepted, ready to merge

#1419 #1413 fix/sfcarousel duplicated slides
  packages/vue/src/components/organisms/SfCarousel/SfCarousel.vue
Labels: hacktoberfest-accepted, ready to merge

#1492 fix: SfAddressPicker doesn't react to "selected" prop changes
  packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue
Labels: hacktoberfest-accepted, ready to merge

#1501 fix: fonts in SfTextarea and add SfTextarea to form example
  packages/shared/styles/components/atoms/SfTextarea.scss
  packages/vue/src/examples/others/form/Form.vue
Labels: hacktoberfest-accepted, ready to merge

#1504 fix: SfMegaMenu confusing on theme
  packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
  packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.stories.js
Labels: hacktoberfest-accepted, ready to merge

#1495 fix: Footer menu opens without clicking on it
  packages/vue/src/utilities/mobile-observer.js
Labels: hacktoberfest-accepted, ready to merge

#1493 fix: sfselect fix v-model and stories
  packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
  packages/vue/src/components/molecules/SfSelect/SfSelect.vue
Labels: hacktoberfest-accepted, ready to merge
