Repository vuestorefront/storefront-ui, pull requests merged in 2020-12, with the labels that each got.

#1530 chore: transfer CI workflow from travis to gh actions
  .github/workflows/on-push-pull-tests.yml
  .travis.yml
  packages/vue/package.json
  yarn.lock
Labels: requested changes, review required

#1560 Refactor SfImage
  packages/shared/styles/components/atoms/SfImage.scss
  packages/shared/styles/components/molecules/SfGallery.scss
  packages/vue/package.json
  packages/vue/src/components/atoms/SfImage/SfImage.md
  packages/vue/src/components/atoms/SfImage/SfImage.spec.js
  packages/vue/src/components/atoms/SfImage/SfImage.stories.js
  packages/vue/src/components/atoms/SfImage/SfImage.stories.scss
  packages/vue/src/components/atoms/SfImage/SfImage.vue
  packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.vue
  packages/vue/src/components/organisms/SfFooter/SfFooter.stories.js
  packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.stories.js
  packages/vue/src/components/organisms/SfGroupedProduct/_internal/SfGroupedProductItem.vue
  packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
  packages/vue/src/components/organisms/SfHeader/SfHeader.vue
  packages/vue/src/examples/pages/checkout/_internal/ConfirmOrder.vue
  packages/vue/src/examples/pages/checkout/_internal/Payment.vue
  packages/vue/src/examples/pages/error/Error.vue
  packages/vue/src/examples/pages/home/Home.vue
  yarn.lock
Labels: review required

#1519 feat: Mobile -popup with information after adding product to the cart
  packages/vue/src/examples/pages/product/Product.vue
Labels: ready to merge
