Repository vuestorefront/storefront-ui, pull requests merged in 2020-07, with the labels that each got.

#1295 fix(docs): link to roadmap fixed
  packages/vue/docs/contributing/become-a-contributor.md
Labels: review required

#1286 feat: add SfHeaderNavigation component
  packages/shared/styles/components/organisms/SfHeader.scss
  packages/shared/styles/components/organisms/SfMegaMenu.scss
  packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
  packages/vue/src/components/organisms/SfHeader/SfHeader.vue
  packages/vue/src/components/organisms/SfHeader/_internal/SfHeaderNavigation.spec.js
  packages/vue/src/components/organisms/SfHeader/_internal/SfHeaderNavigation.vue
  packages/vue/src/components/organisms/SfHeader/_internal/SfHeaderNavigationItem.vue
  packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.stories.js
  packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.vue
Labels: review required

#1212 feat: SfImage add webp and different formats of src and srcset
  packages/shared/styles/components/atoms/SfImage.scss
  packages/vue/public/assets/storybook/SfImage/product-109x164.webp
  packages/vue/public/assets/storybook/SfImage/product-216x326.webp
  packages/vue/src/components/atoms/SfImage/SfImage.stories.js
  packages/vue/src/components/atoms/SfImage/SfImage.vue
Labels: requested changes, review required

#1250 [WIP] refactor: new styles for guide
  packages/shared/styles/helpers/_breakpoints.scss
  packages/shared/styles/variables/_typography.scss
  packages/vue/docs/.vuepress/config.js
  packages/vue/docs/migration-guide.md
Labels: requested changes

#1315 fix: SfPagination number slot fix
  packages/vue/src/components/molecules/SfPagination/SfPagination.stories.js
Labels: review required

#1265 fix: no possibility to override SfIcon size in SfSearchbar
  packages/vue/docs/migration-guide.md
  packages/vue/src/components/molecules/SfSearchBar/SfSearchBar.stories.js
  packages/vue/src/components/molecules/SfSearchBar/SfSearchBar.vue
Labels: review required
