Repository vuestorefront/storefront-ui, pull requests merged in 2020-11, with the labels that each got.

#1430 fix: conditional SfLnk in SfCollectedProduct
  packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.stories.js
  packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.vue
Labels: hacktoberfest-accepted, ready to merge

#1431 fix: SfPagination pass link as string
  packages/vue/src/components/molecules/SfPagination/SfPagination.vue
Labels: hacktoberfest-accepted, ready to merge

#1432 fix: SfProductCard isAddedToCart prop not changing icon
  packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
Labels: hacktoberfest-accepted, ready to merge

#1435 #1421 Fix SFInput label on addition of placeholder value
  packages/shared/styles/components/atoms/SfInput.scss
Labels: hacktoberfest-accepted, ready to merge

#1439 fix: SfGallery error with enableZoom
  packages/shared/styles/components/molecules/SfGallery.scss
  packages/vue/src/components/molecules/SfGallery/SfGallery.stories.js
  packages/vue/src/components/molecules/SfGallery/SfGallery.vue
Labels: hacktoberfest-accepted, ready to merge

#1448 #1428 - [BUG] SfCardHorizontal size and color change from property to select
  packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.stories.js
Labels: hacktoberfest-accepted, ready to merge

#1459 fix: Unable to find uri in background in SfSelect
  packages/shared/styles/components/molecules/SfSelect.scss
Labels: hacktoberfest-accepted, ready to merge

#1461 fix(modal): add type button to SfModal stories
  packages/vue/src/components/molecules/SfModal/SfModal.stories.js
Labels: hacktoberfest-accepted, ready to merge

#1463 fix: SfCircleIcon in disabled state with color modifier
  packages/shared/styles/components/atoms/SfCircleIcon.scss
Labels: hacktoberfest-accepted, ready to merge

#1464 fix: SfArrow with transparent modifier on disbaled mode
  packages/shared/styles/components/atoms/SfArrow.scss
Labels: hacktoberfest-accepted, ready to merge

#1476 fix: button text modifier color changed
  packages/shared/styles/components/atoms/SfButton.scss
Labels: hacktoberfest-accepted, ready to merge

#1465 fix: jest tests console bugs fix
  packages/vue/src/components/atoms/SfTexarea/SfTextarea.spec.js
  packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.spec.js
  packages/vue/src/components/organisms/SfTabs/_internal/SfTab.spec.js
Labels: hacktoberfest-accepted, ready to merge

#1470 fix: updated link to our new designs in figma
  packages/vue/docs/contributing/become-a-contributor.md
  packages/vue/docs/design/working-with-designs.md
Labels: hacktoberfest-accepted, ready to merge

#1472 fix: styles for hover buttons in story variant
  packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.stories.js
Labels: hacktoberfest-accepted, ready to merge

#1484 fix: apply new designs in storybook
  packages/vue/src/components/organisms/SfAccordion/_internal/SfAccordionItem.vue
  packages/vue/src/examples/pages/category/Category.vue
Labels: hacktoberfest-accepted, ready to merge

#1487 fix: color and background for remove btn in SfCollectedProduct
  packages/shared/styles/components/organisms/SfCollectedProduct.scss
Labels: hacktoberfest-accepted, ready to merge

#1488 fix: button type for buttons in SfBar
  packages/vue/src/components/molecules/SfBar/SfBar.vue
Labels: hacktoberfest-accepted, ready to merge

#1489 fix: updated config for tailwind
  packages/vue/docs/getting-started/customization.md
Labels: hacktoberfest-accepted, ready to merge

#1498 fix: nullish propagation in sfimage
  packages/vue/src/components/atoms/SfImage/SfImage.vue
Labels: ready to merge

#1508 fix: SfColorPicker opacity affects SfColor
  packages/shared/styles/components/molecules/SfColorPicker.scss
  packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.vue
Labels: ready to merge

#1503 fix: border color change
  packages/shared/styles/components/molecules/SfComponentSelect.scss
  packages/shared/styles/components/molecules/SfSelect.scss
  packages/vue/src/components/molecules/SfSelect/SfSelect.vue
Labels: review required

#1515 feat: SfBanner adding prop for button link
  packages/shared/styles/components/molecules/SfBanner.scss
  packages/vue/docs/introduction/releases.md
  packages/vue/src/components/molecules/SfBanner/SfBanner.stories.js
  packages/vue/src/components/molecules/SfBanner/SfBanner.vue
  packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
  packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
Labels: ready to merge

#1522 fix: sfimage fix in story, add progressive lazy loading with story
  packages/vue/src/components/atoms/SfImage/SfImage.stories.js
  packages/vue/src/components/atoms/SfImage/SfImage.vue
Labels: ready to merge

#1523 Chore: change release docs
  packages/vue/docs/.vuepress/config.js
  packages/vue/docs/releases/README.md
  packages/vue/docs/releases/v0.9.0.md
  packages/vue/docs/releases/v0.9.1.md
  packages/vue/docs/releases/v0.9.2.md
  packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
Labels: ready to merge

#1524 fix: tbody and thead in SfTable
  packages/vue/src/components/organisms/SfTable/_internal/SfTableHeading.spec.js
  packages/vue/src/components/organisms/SfTable/_internal/SfTableHeading.vue
  packages/vue/src/components/organisms/SfTable/_internal/SfTableRow.spec.js
  packages/vue/src/components/organisms/SfTable/_internal/SfTableRow.vue
Labels: ready to merge

#1527 feat: SfCallToAction add link prop
  packages/vue/src/components/molecules/SfCallToAction/SfCallToAction.stories.js
  packages/vue/src/components/molecules/SfCallToAction/SfCallToAction.vue
Labels: ready to merge

#1528 feat: SfHero add link prop and wrapper for component
  packages/shared/styles/components/organisms/SfHero.scss
  packages/vue/src/components/organisms/SfHero/SfHero.stories.js
  packages/vue/src/components/organisms/SfHero/_internal/SfHeroItem.vue
Labels: ready to merge
