Repository vuestorefront/storefront-ui, pull requests merged in 2020-05, with the labels that each got.

#1143 fix: SfHeader click moved to button
  packages/shared/styles/components/organisms/SfHeader.scss
  packages/vue/src/components/organisms/SfHeader/SfHeader.vue
Labels: ready to merge

#1135 fix: typo in SfHero stories
  packages/vue/src/components/organisms/SfHero/SfHero.stories.js
Labels: review required

#1145 fix: SfCheckbox cursor on checkbox input behaviour fixed
  packages/shared/styles/components/atoms/SfCheckbox.scss
  packages/shared/styles/components/molecules/SfRadio.scss
Labels: requested changes

#1133 fix: change button to div on SfBottomNavigation
  packages/shared/styles/components/organisms/SfBottomNavigation.scss
  packages/vue/src/components/organisms/SfBottomNavigation/_internal/SfBottomNavigationItem.vue
Labels: ready to merge

#1077 docs: add customizable global variables
  packages/vue/docs/customization.md
Labels: review required

#1076 doc: categories in components docs
  packages/vue/docs/.vuepress/config.js
  packages/vue/docs/.vuepress/enhanceApp.js
  packages/vue/docs/assets/members.json
  packages/vue/scripts/create-vue-components-docs.js
Labels: review required

#1163 fix: SfHeader sticky with a gap to hide
  packages/vue/src/components/organisms/SfHeader/SfHeader.vue
Labels: review required

#1122 Fix: SfSelect add no-chevron modifier, remove padding
  packages/shared/styles/components/molecules/SfSelect.scss
  packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
Labels: ready to merge

#1131 fix: more descriptive aria labels for buttons
  packages/vue/src/components/atoms/SfColor/SfColor.stories.js
  packages/vue/src/components/atoms/SfInput/SfInput.stories.js
  packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.vue
  packages/vue/src/components/molecules/SfNotification/SfNotification.vue
  packages/vue/src/components/organisms/SfBannerGrid/SfBannerGrid.stories.js
  packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.vue
  packages/vue/src/components/organisms/SfGroupedProduct/_internal/SfGroupedProductItem.vue
  packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
  packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.vue
Labels: review required

#1095 a11y: SfSelect with v-focus
  packages/shared/styles/components/molecules/SfSelect.scss
  packages/vue/src/components/molecules/SfSelect/SfSelect.vue
  packages/vue/src/components/molecules/SfSelect/_internal/SfSelectOption.vue
Labels: review required

#1018 feat: sftabs remove jump effect
  packages/vue/src/components/molecules/SfScrollable/SfScrollable.vue
  packages/vue/src/components/organisms/SfTabs/SfTabs.stories.js
  packages/vue/src/components/organisms/SfTabs/SfTabs.vue
  packages/vue/src/components/organisms/SfTabs/_internal/SfTab.vue
Labels: review required

#1099 feat: click outside directive
  packages/vue/src/components/molecules/SfDropdown/SfDropdown.stories.js
  packages/vue/src/components/molecules/SfDropdown/SfDropdown.vue
  packages/vue/src/components/molecules/SfModal/SfModal.vue
  packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
  packages/vue/src/components/molecules/SfSelect/SfSelect.vue
  packages/vue/src/utilities/directives/click-outside/click-outside-directive.js
  packages/vue/src/utilities/directives/index.js
Labels: review required

#1012 feat(component): SfColorPicker
  packages/shared/styles/components/molecules/SfColorPicker.scss
  packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.md
  packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.spec.js
  packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.stories.js
  packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.vue
  packages/vue/src/examples/pages/category/Category.vue
Labels: review required

#1185 refactor: price variant as elements
  packages/shared/styles/components/atoms/SfPrice.scss
  packages/vue/src/components/atoms/SfPrice/SfPrice.spec.js
  packages/vue/src/components/atoms/SfPrice/SfPrice.vue
Labels: review required

#1223 #1213 fix/sfselect accessibility violations
  packages/vue/src/components/molecules/SfSelect/SfSelect.vue
Labels: review required

#1218 fix: change label size in select and input
  packages/shared/styles/components/atoms/SfInput.scss
  packages/shared/styles/components/molecules/SfSelect.scss
Labels: review required
