Repository vuestorefront/storefront-ui, pull requests merged in 2023-06, with the labels that each got.

#2466 fix: SfQuantitySelector: set 0 as the minimum
  packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue
  packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
Labels: v1.x.x

#2498 fix: links those are not reachable, or have duplicate entries
  packages/vue/src/stories/2. Websites.stories.mdx
Labels: v1.x.x

#2795 fix(nuxt): use @storefront-ui/vue as workspace dep [SFUI2-1237] #2793
  CHANGELOG.md
  packages/sfui/frameworks/nuxt/package.json
  yarn.lock
Labels: bug

#2511 improvement: the release section structure in storybook
  packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
  packages/vue/src/stories/releases/v0.13.x/v0.13.2/v0.13.2.stories.mdx
  packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
  packages/vue/src/stories/releases/v0.13.x/v0.13.5/v0.13.5.stories.mdx
  packages/vue/src/stories/releases/v0.13.x/v0.13.6/v0.13.6.stories.mdx
  packages/vue/src/stories/releases/v0.13.x/v0.13.7/v0.13.7.stories.mdx
Labels: v1.x.x

#2819 feat: productSlider [SFUI2-1190]
  .changeset/beige-coins-argue.md
  apps/docs/components/.vuepress/public/thumbnails/blocks/ProductSlider.png
  apps/docs/components/blocks/ProductSlider.md
  apps/docs/components/blocks/Review.md
  apps/preview/next/pages/showcases/ProductSlider/Basic.tsx
  apps/preview/nuxt/pages/showcases/ProductSlider/Basic.vue
  packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
Labels: feature

#2836 fix: ring instead of border on add to wishlist
  apps/preview/next/pages/showcases/ProductCard/ProductCardVertical.tsx
  apps/preview/next/pages/showcases/ProductSlider/Basic.tsx
  apps/preview/nuxt/pages/showcases/ProductCard/ProductCardVertical.vue
  apps/preview/nuxt/pages/showcases/ProductSlider/Basic.vue
Labels: bug

#2838 docs: accessibility notes should be closer to top of the page
  apps/docs/components/blocks/Gallery.md
  apps/docs/components/blocks/ProductSlider.md
Labels: bug

#2837 fix: focus border around image is not visible
  apps/docs/components/blocks/Gallery.md
  apps/docs/components/blocks/ProductSlider.md
  apps/preview/next/pages/showcases/ProductCard/ProductCardVertical.tsx
  apps/preview/next/pages/showcases/ProductSlider/Basic.tsx
  apps/preview/nuxt/pages/showcases/ProductCard/ProductCardVertical.vue
  apps/preview/nuxt/pages/showcases/ProductSlider/Basic.vue
Labels: bug

#2855 fix: broken blocks link
  apps/docs/components/components/link.md
Labels: bug

#2871 fix: remove glide instance on component destroy [SFUI2-1261]
  packages/vue/src/components/organisms/SfCarousel/SfCarousel.vue
  packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.vue
  packages/vue/src/components/organisms/SfHero/SfHero.vue
Labels: bug

#2867 docs: add tip about global variables
  packages/vue/src/stories/getting-started/2. development guide/1. customization.stories.mdx
Labels: docs

#2877 fix: update v1 links [SFUI2-1264]
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  packages/vue/package.json
  packages/vue/src/components/atoms/SfOverlay/SfOverlay.stories.js
  packages/vue/src/components/molecules/SfBottomModal/SfBottomModal.stories.js
  packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.stories.js
  packages/vue/src/components/molecules/SfModal/SfModal.stories.js
  packages/vue/src/components/organisms/SfAccordion/SfAccordion.stories.js
  packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.stories.js
  packages/vue/src/components/templates/SfPayment/SfPayment.stories.js
  packages/vue/src/components/templates/SfPersonalDetails/SfPersonalDetails.stories.js
  packages/vue/src/components/templates/SfShippingDetails/SfShippingDetails.stories.js
  packages/vue/src/stories/1. Introduction.stories.mdx
Labels: bug
